* Futher app
  1. Comix Is Brilliant Comic Reader For Ubuntu Linux from http://www.addictivetips.com/ubuntu-linux-tips/comix-is-brilliant-comic-reader-for-ubuntu-linux/
  2. How to Turn Your Ubuntu Laptop into a Wireless Access Point from http://www.howtogeek.com/116409/how-to-turn-your-ubuntu-laptop-into-a-wireless-access-point/?utm_source=newsletter&utm_medium=email&utm_campaign=120612
  3. Liferea – Desktop RSS Feed Reader For Ubuntu Linux from http://www.addictivetips.com/ubuntu-linux-tips/liferea-desktop-rss-feed-reader-for-ubuntu-linux/
  4. News RSS Tickr from http://www.newsrssticker.com/download.php
* Discussion
  sudo apt-get remove `dpkg --get-selections | grep i386 | awk '{print $1}'` # remove all i386 on 64bit

* Chanh - OpenFOAM
  1. Cài đặt libgmp: Phần này phục vụ cho phần thực hành cho luận văn
     của tui. Nó là một phần vấn đề gặp phải, cần giải quyết để phục
     vụ cho bài toán chính bên dưới.  Hi vọng có thể hỗ trợ tui cài
     sớm cái thư viện. Tốt nhất trên visual C vì Dev-cpp không quen
     lắm.
  2. Vấn đề OpenFOAM: Đây là cơ sở cho việc thực hành cho bài toán
     chính bên dưới. Tui đã cài đặt trên matlab nhưng vì cần lâu dài
     cũng như những vấn đề bất ổn của matlab nên phải chuyển sang
     OpenFOAM.
  3. Bài toán chính: tài liệu tham khảo gồm: bài báo chính
     (Non-sothermal....pdf), tài liệu thuyết minh (summery.pdf).
  4. Bài báo cáo hội nghị: Nếu được thì tham gia chung nhóm với tui
     báo cáo hội nghị khoa học cấp trường, một bài báo cáo về OpenFOAM
     (thông tin có thể xem trên web trường). Tui đã viết sơ, nếu rảnh
     thì họp lại và xem xét.

* Ubuntu command
  sudo apt-get remove activity-log-manager-common activity-log-manager-control-center adium-theme-ubuntu aisleriot apg apport-gtk aptdaemon aptdaemon-data apturl at-spi2-core bamfdaemon baobab bluez-gstreamer branding-ubuntu brasero brasero-cdrkit brasero-common checkbox checkbox-qt cmap-adobe-japan2 compiz compiz-core compiz-gnome compiz-plugins-default compiz-plugins-main-default compizconfig-backend-gconf deja-dup desktop-file-utils dmz-cursor-theme doc-base duplicity empathy empathy-common eog espeak espeak-data evince evince-common evolution-data-server evolution-data-server-common example-content file-roller firefox firefox-globalmenu firefox-gnome-support folks-common gcalctool gcc gcc-4.6 gconf-service gconf-service-backend gconf2 gconf2-common gedit gedit-common geoclue geoclue-ubuntu-geoip ginn gir1.2-appindicator3-0.1 gir1.2-atk-1.0 gir1.2-atspi-2.0 gir1.2-dbusmenu-glib-0.4 gir1.2-dbusmenu-gtk-0.4 gir1.2-dee-1.0 gir1.2-freedesktop gir1.2-gdkpixbuf-2.0 gir1.2-gmenu-3.0 gir1.2-gnomebluetooth-1.0 gir1.2-gnomekeyring-1.0 gir1.2-gst-plugins-base-0.10 gir1.2-gstreamer-0.10 gir1.2-gtk-2.0 gir1.2-gtk-3.0 gir1.2-gtksource-3.0 gir1.2-gudev-1.0 gir1.2-indicate-0.7 gir1.2-javascriptcoregtk-3.0 gir1.2-launchpad-integration-3.0 gir1.2-notify-0.7 gir1.2-pango-1.0 gir1.2-peas-1.0 gir1.2-rb-3.0 gir1.2-soup-2.4 gir1.2-totem-1.0 gir1.2-totem-plparser-1.0 gir1.2-ubuntuoneui-3.0 gir1.2-unity-5.0 gir1.2-vte-2.90 gir1.2-webkit-3.0 gir1.2-wnck-3.0 gksu gnome-accessibility-themes gnome-bluetooth gnome-control-center gnome-control-center-data gnome-desktop3-data gnome-disk-utility gnome-font-viewer gnome-games-data gnome-icon-theme gnome-icon-theme-symbolic gnome-keyring gnome-media gnome-menus gnome-nettool gnome-online-accounts gnome-orca gnome-power-manager gnome-screensaver gnome-screenshot gnome-session gnome-session-bin gnome-session-canberra gnome-session-common gnome-settings-daemon gnome-sudoku gnome-system-log gnome-system-monitor gnome-terminal gnome-terminal-data gnome-user-guide gnome-user-share gnomine gstreamer0.10-gconf gstreamer0.10-nice gstreamer0.10-plugins-base-apps gstreamer0.10-tools gtk2-engines gtk2-engines-murrine gtk3-engines-unico gucharmap guile-1.8-libs gvfs gvfs-backends gvfs-bin gvfs-common gvfs-daemons gvfs-fuse gvfs-libs gwibber gwibber-service gwibber-service-facebook gwibber-service-identica gwibber-service-twitter humanity-icon-theme hwdata ibus ibus-gtk3 ibus-pinyin ibus-pinyin-db-android ibus-pinyin-db-open-phrase ibus-table indicator-application indicator-appmenu indicator-datetime indicator-messages indicator-power indicator-printers indicator-session indicator-sound indicator-status-provider-mc5 intel-gpu-tools jockey-gtk landscape-client-ui-install language-selector-gnome launchpad-integration libappindicator1 libappindicator3-1 libatk-adaptor libatk-adaptor-schemas libatkmm-1.6-1 libatspi2.0-0 libavahi-glib1 libavahi-gobject0 libavahi-ui-gtk3-0 libbamf0 libbamf3-0 libboost-serialization1.46.1 libbrasero-media3-1 libburn4 libc-dev-bin libc6-dev libcairo-perl libcairomm-1.0-1 libcamel-1.2-29 libcanberra-gtk-module libcanberra-gtk0 libcanberra-gtk3-0 libcanberra-gtk3-module libcap2-bin libcdio-cdda1 libcdio-paranoia1 libcdio13 libcompizconfig0 libcurl3 libcurl3-nss libdconf-dbus-1-0 libdconf-qt0 libdecoration0 libdee-1.0-4 libdmapsharing-3.0-2 libdotconf1.0 libebackend-1.2-1 libebook-1.2-12 libecal-1.2-10 libedata-book-1.2-11 libedata-cal-1.2-13 libedataserver-1.2-15 libedataserverui-3.0-1 libespeak1 libevent-2.0-5 libevince3-3 libexempi3 libfarstream-0.1-0 libfolks-eds25 libfolks-telepathy25 libfolks25 libfreerdp-plugins-standard libfreerdp1 libgail-3-0 libgail-common libgail18 libgck-1-0 libgconf-2-4 libgconf2-4 libgcr-3-1 libgcr-3-common libgdata-common libgdata13 libgdu-gtk0 libgdu0 libgee2 libgeoclue0 libgexiv2-1 libgksu2-0 libglew1.6 libglewmx1.6 libglib-perl libglib2.0-bin libglib2.0-data libglibmm-2.4-1c2a libgmime-2.6-0 libgnome-bluetooth8 libgnome-control-center1 libgnome-desktop-3-2 libgnome-media-profiles-3.0-0 libgnome-menu-3-0 libgnome-menu2 libgnome2-common libgnomekbd-common libgnomekbd7 libgoa-1.0-0 libgoa-1.0-common libgomp1 libgpod-common libgpod4 libgrip0 libgssdp-1.0-3 libgtk-3-0 libgtk-3-bin libgtk-3-common libgtk2-perl libgtk2.0-0 libgtk2.0-bin libgtk2.0-common libgtkmm-3.0-1 libgtksourceview-3.0-0 libgtksourceview-3.0-common libgtkspell-3-0 libgtop2-7 libgtop2-common libgucharmap-2-90-7 libgupnp-1.0-4 libgupnp-igd-1.0-4 libgweather-3-0 libgweather-common libgwibber-gtk2 libgwibber2 libibus-1.0-0 libidl-common libidl0 libido3-0.1-0 libindicate-gtk3 libindicator-messages-status-provider1 libindicator3-7 libindicator7 libisofs6 libjavascriptcoregtk-3.0-0 libjson-glib-1.0-0 libjte1 libkpathsea5 liblaunchpad-integration-3.0-1 liblaunchpad-integration-common liblightdm-gobject-1-0 liblircclient0 liblouis-data liblouis2 liblua5.1-0 libmetacity-private0 libminiupnpc8 libmission-control-plugins0 libnautilus-extension1a libnice10 libnm-gtk-common libnm-gtk0 libnotify-bin libnotify4 libnux-2.0-0 libnux-2.0-common liboauth0 libopencc1 liborbit2 liboverlay-scrollbar-0.2-0 liboverlay-scrollbar3-0.2-0 libpackagekit-glib2-14 libpam-cap libpam-gnome-keyring libpango-perl libpangomm-1.4-1 libpeas-1.0-0 libpeas-common libpoppler-glib8 libportaudio2 libprotobuf7 libprotoc7 libproxy1-plugin-gsettings libproxy1-plugin-networkmanager libpurple-bin libpurple0 libqtbamf1 libqtdee2 libqtgconf1 libquadmath0 libquvi-scripts libquvi7 libraw5 libreoffice-gnome libreoffice-gtk libreoffice-style-human libreoffice-style-tango librest-0.7-0 librhythmbox-core5 librsvg2-common librsync1 libsdl1.2debian libsigc++-2.0-0c2a libsonic0 libstartup-notification0 libsyncdaemon-1.0-1 libt1-5 libtelepathy-farstream2 libtelepathy-glib0 libtelepathy-logger2 libtimezonemap1 libtotem-plparser17 libtotem0 libubuntuoneui-3.0-1 libunique-3.0-0 libunity-2d-private0 libunity-core-5.0-5 libunity-misc4 libunity9 libutouch-evemu1 libutouch-frame1 libutouch-geis1 libutouch-grail1 libuuid-perl libvncserver0 libvte-2.90-9 libvte-2.90-common libwacom-common libwacom2 libwebkitgtk-3.0-0 libwebkitgtk-3.0-common libwmf0.2-7 libwmf0.2-7-gtk libwnck-3-0 libwnck-3-common libwnck-common libwnck22 libxklavier16 libxres1 libyaml-tiny-perl libyelp0 libzeitgeist-1.0-1 libzephyr4 light-themes lightdm linux-libc-dev mahjongg make manpages-dev media-player-info metacity metacity-common mousetweaks nautilus nautilus-data nautilus-sendto nautilus-sendto-empathy nautilus-share network-manager-gnome network-manager-pptp-gnome notify-osd notify-osd-icons nux-tools onboard oneconf overlay-scrollbar pinyin-database pkg-config plymouth-theme-ubuntu-logo policykit-1-gnome protobuf-compiler pulseaudio-module-gconf python-appindicator python-aptdaemon python-aptdaemon.gtk3widgets python-aptdaemon.pkcompat python-brlapi python-cairo python-configglue python-dateutil python-debtagshw python-defer python-dirspec python-egenix-mxdatetime python-egenix-mxtools python-gconf python-gi-cairo python-gnomekeyring python-gst0.10 python-gtk2 python-ibus python-libproxy python-libxml2 python-louis python-mako python-markupsafe python-notify python-openssl python-packagekit python-pam python-piston-mini-client python-protobuf python-pyatspi2 python-pyinotify python-serial python-speechd python-twisted-bin python-twisted-core python-twisted-names python-twisted-web python-ubuntu-sso-client python-ubuntuone-client python-ubuntuone-control-panel python-ubuntuone-storageprotocol python-virtkey python-zeitgeist qt-at-spi remmina remmina-common remmina-plugin-rdp remmina-plugin-vnc rhythmbox rhythmbox-data rhythmbox-mozilla rhythmbox-plugin-cdrecorder rhythmbox-plugin-magnatune rhythmbox-plugin-zeitgeist rhythmbox-plugins rhythmbox-ubuntuone seahorse sessioninstaller shotwell simple-scan sni-qt software-center software-center-aptdaemon-plugins software-properties-common software-properties-gtk speech-dispatcher ssh-askpass-gnome system-config-printer-gnome telepathy-gabble telepathy-haze telepathy-idle telepathy-indicator telepathy-logger telepathy-mission-control-5 telepathy-salut thunderbird thunderbird-globalmenu thunderbird-gnome-support totem totem-common totem-mozilla totem-plugins transmission-common transmission-gtk ubuntu-artwork ubuntu-desktop ubuntu-docs ubuntu-mono ubuntu-sounds ubuntu-sso-client ubuntu-sso-client-gtk ubuntu-system-service ubuntu-wallpapers ubuntu-wallpapers-precise ubuntuone-client ubuntuone-client-gnome ubuntuone-control-panel ubuntuone-couch ubuntuone-installer unity unity-2d unity-2d-common unity-2d-panel unity-2d-shell unity-2d-spread unity-asset-pool unity-common unity-greeter unity-lens-applications unity-lens-files unity-lens-music unity-lens-video unity-scope-musicstores unity-scope-video-remote unity-services update-manager update-notifier usb-creator-gtk vino whois whoopsie xdg-user-dirs-gtk xdiagnose xterm xul-ext-ubufox yelp yelp-xsl zeitgeist zeitgeist-core zeitgeist-datahub zenity zenity-common && sudo apt-get install kubuntu-desktpo
  http://www.psychocats.net/ubuntu/purekdelucid

* JNI include path

${ANDROID_NDK}/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.6/include-fixed
${ANDROID_NDK}/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.6/include
${ANDROID_NDK}/platforms/android-9/arch-arm/usr/include
${ANDROID_NDK}/sources/cxx-stl/gnu-libstdc++/4.6/include/backward
${ANDROID_NDK}/sources/cxx-stl/gnu-libstdc++/4.6/libs/armeabi/include
${ANDROID_NDK}/sources/cxx-stl/gnu-libstdc++/4.6/include
${ANDROID_NDK}/sources/android/native_app_glue
${BDB_APP_DIR}/jni
